version: '3.8'

services:

  app:
    build:
      context: challenge
      dockerfile: Dockerfile
    image: gcr.io/glowing-reserve-336013/xexe
    ports:
      - '3009:8000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl -I --fail http://localhost:8000/ || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
